Rails.application.routes.draw do
  root 'setup#index'
  get 'setup/login'
  post 'setup/login'
  get 'setup/employees'
  post 'setup/employees'
  get 'setup/signup'
  post 'setup/signup'
  post 'setup/create'
  post 'setup/delete'
  get 'setup/delete'
  get 'setup/edit'
  post 'setup/edit'
  get 'setup/update'
  post 'setup/update'

  get 'document/index'
  post 'document/index'
  get 'document/new'
  post 'document/new'
  get 'document/edit'
  post 'document/edit'
  get  'document/create'
  post 'document/create'
  get 'document/alldocuments'
  post 'document/alldocuments'

end
